name: build_ffi_generator
description: Builder to generate ffi bindings from a textual description
publish_to: none
version: 0.1.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  build: ^2.0.0
  dart_style: ^2.0.1
  meta: ^1.3.0
  charcode: ^1.2.0
  source_span: ^1.8.1

dev_dependencies:
  pedantic: ^1.8.0
  build_runner: ^2.0.0
  test: ^1.17.0
  simons_pub_uploader:
    hosted:
      url: https://simonbinder.eu
      name: simons_pub_uploader
    version: ^1.0.4
